### ISSUE TITLE
Batching

### ISSUE THREAD

**Issue by whitead** [ur-whitelab/BO-LIFT#6]
![image](https://user-images.githubusercontent.com/908389/218241849-e6c7dd14-c6ca-4bc7-a275-b54bce4c8ce7.png)

**Comment by kjappelbaum** [comment]
Did you try this? I found performance to drop quite a bit when I tried to batch queries - but maybe I didn't use it correctly.

**Comment by whitead** [comment]
@kjappelbaum No, did not end up trying it. Thanks for the insight! Will close it then for now
